baseURL = "http://regis.doseextra.com/"
languageCode = "pt-br"
title = "Regis Tomkiel"
theme = "hugo-theme-sarah"

[permalinks]
fixed = ":title/"
blog  = ":slug"
paginas = "/:filename"

[params]
author = "Regis Tomkiel"
keywords = ["Desenvolvedor Web", "Podcaster", "Entusiasta de Software Livre"]
avatar = "https://avatars2.githubusercontent.com/u/15989303?s=400&u=9eb0f3fdfa13bc817d392cecd23966f4ec51fea2&v=4"
dateform = "Jan 2, 2006"
lang = "pt"
footertext = "Escrito por Régis Tomkiel"
googleAnalytics = "rr"
about = "Desenvolvedor Web e administrador de sistemas unix-like (*bsd e GNU/Linux). Skills interessantes em PHP, Shell Script, Go, Wordpress*, Hugo e SEO."

[params.social]
linkedin      = "regis-tomkiel"
twitter       = "tomtomkiel"
github        = "rtomkiel"

[[params.info]]
label = "Address"
value = "Bento Gonçalves, RS, Brasil"

[[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 1
  url = "/"

[[menu.main]]
  name = "Páginas"
  identifier = "paginas"
  weight = 2
  url = "/paginas/"

[[menu.main]]
  name = "Artigos"
  identifier = "artigos"
  weight = 3
  url = "/artigos/"

[[menu.main]]
  name = "Podcasts"
  identifier = "podcasts"
  weight = 4
  url = "/podcasts/"
